//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComposantsLogiciels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employe()
        {
            this.LesDiplomes = new HashSet<Diplome>();
        }
    
        public int emp_id { get; set; }
        public string emp_nom { get; set; }
        public string emp_prenom { get; set; }
        public string emp_sexe { get; set; }
        public Nullable<bool> emp_cadre { get; set; }
        public Nullable<decimal> emp_salaire { get; set; }
        public Nullable<int> emp_service { get; set; }
    
        public virtual Service LeService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diplome> LesDiplomes { get; set; }
    }
}
